name: Auto-merge

on:
  workflow_run:
    types: [completed]
    branches-ignore: [master]
    workflows: ["CI Suite"]

jobs:
  merge:
    name: Merge compatible dependency upgrades
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge Successful Dependabot
        uses: actions/github-script@v4.0.2
        if: |
          github.actor == 'dependabot[bot]' &&
          github.event.workflow_run.conclusion == 'success'
        with:
          github-token: ${{github.token}}
          script: |
            const root = process.env.GITHUB_WORKSPACE;
            const main = require(
              `${root}/.github/workflows/scripts/merge-compatible-upgrades`
            );
            main({
              github,
              context,
            });
